---

- name: Add armhf
  ansible.builtin.shell: dpkg --add-architecture armhf >/etc/armhf-dpkg.log
  args:
    creates: /etc/armhf-dpkg.log
  become: true

- name: Run "apt-get update"
  ansible.builtin.apt:
    update_cache: yes
  become: true

# https://github.com/ptitSeb/box86/blob/master/docs/COMPILE.md
- name: Get sources.list
  ansible.builtin.get_url:
    url: https://itai-nelken.github.io/weekly-box86-debs/debian/box86.list
    dest: /etc/apt/sources.list.d/box86.list
  become: true

- name: Add an Apt signing key
  ansible.builtin.apt_key:
    id: EB3CE9A337ECDFA4
    url: https://itai-nelken.github.io/weekly-box86-debs/debian/KEY.gpg
    keyring: /etc/apt/trusted.gpg.d/box86-debs-archive-keyring.gpg
  become: true

- name: Install Box86 for ARM64
  ansible.builtin.apt:
    pkg:
    - box86:armhf
  when: ansible_architecture == "aarch64"
  become: true
  notify: restart systemd-binfmt


- name: Install Box86
  ansible.builtin.apt:
    pkg:
    - box86
  when: ansible_architecture == "armhf"
  become: true
  notify: restart systemd-binfmt